### ISSUE TITLE
Segmentation on personal dataset

### ISSUE THREAD

**Issue by titusadt** [Wuziyi616/SlotDiffusion#2]
Hi, your work looks great, and I am tryin to use it to segment my own images. and I am just unsure of how I would go about that. I was thinking of using the pretrained weights and  CLEVRTex, what confuses me is figuring out where to insert my input data. Any suggestions would be helpful, thank you

**Comment by Wuziyi616** [comment]
Hi thanks for your interest in our work.
[This](https://github.com/Wuziyi616/SlotDiffusion/blob/main/slotdiffusion/img_based/test_seg.py) is the file we use for evaluating image segmentation. Maybe replace the input image with your images.

**Comment by titusadt** [comment]
Thank you for the reply! I was able to test the model with my own images. 

However, I dont know how to get the output data. Like with my input image, I want a segmented image as the output (and maybe masking information) as in your examples but I am unsure of how to generate. I looked at the nerv directory and saw scripts on writing out the image data and was wondering if that was how to get the segmented image output.

Please let me know how I can go about generating the output, and suggestions would be appreciated, thank you.
