### ISSUE TITLE
Getting segmented image

### ISSUE THREAD

**Issue by titusadt** [Wuziyi616/SlotDiffusion#3]
Thank you for the reply on the last post! I was able to test the model with my own images.

However, I dont know how to get the output data. Like with my input image, I want a segmented image as the output (and maybe masking information) as in your examples but I am unsure of how to generate. I looked at the nerv directory and saw scripts on writing out the image data and was wondering if that was how to get the segmented image output.

Please let me know how I can go about generating the output, and suggestions would be appreciated, thank you

**Comment by Wuziyi616** [comment]
I don't see the question here -- isn't [this](https://github.com/Wuziyi616/SlotDiffusion/blob/f3f9fc906e37292a947fa2af5d8f2a89153fa97d/slotdiffusion/img_based/test_seg.py#L75) `pred_masks` what you want?

The easiest way to get a masked image is to use (you may need to adjust some dimension here) my provided function [here](https://github.com/Wuziyi616/SlotDiffusion/blob/f3f9fc906e37292a947fa2af5d8f2a89153fa97d/slotdiffusion/video_based/vis.py#L41). Then you can just save it using whatever library you want like matplotlib or PIL.Image.

**Comment by Wuziyi616** [comment]
It's hard to give further information cause this is about basic python. I will close this issue for now.
